/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as rootRootLayoutRouteImport } from './routes/(root)/_rootLayout'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as rootRootLayoutIndexRouteImport } from './routes/(root)/_rootLayout/index'
import { Route as vendorVendorVendorLayoutRouteImport } from './routes/(vendor)/vendor/_vendorLayout'
import { Route as rootRootLayoutTermsRouteImport } from './routes/(root)/_rootLayout/terms'
import { Route as rootRootLayoutSearchRouteImport } from './routes/(root)/_rootLayout/search'
import { Route as rootRootLayoutPrivacyRouteImport } from './routes/(root)/_rootLayout/privacy'
import { Route as rootRootLayoutCookiesRouteImport } from './routes/(root)/_rootLayout/cookies'
import { Route as rootRootLayoutContactRouteImport } from './routes/(root)/_rootLayout/contact'
import { Route as rootRootLayoutAuthenticatedRouteImport } from './routes/(root)/_rootLayout/_authenticated'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/_auth/signup'
import { Route as authAuthResetPasswordRouteImport } from './routes/(auth)/_auth/reset-password'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth/login'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/_auth/forgot-password'
import { Route as adminAdminAdminLayoutRouteImport } from './routes/(admin)/admin/_adminLayout'
import { Route as vendorVendorVendorLayoutIndexRouteImport } from './routes/(vendor)/vendor/_vendorLayout/index'
import { Route as rootRootLayoutProductsIndexRouteImport } from './routes/(root)/_rootLayout/products/index'
import { Route as rootRootLayoutCategoriesIndexRouteImport } from './routes/(root)/_rootLayout/categories/index'
import { Route as adminAdminAdminLayoutIndexRouteImport } from './routes/(admin)/admin/_adminLayout/index'
import { Route as rootRootLayoutProductsSlugRouteImport } from './routes/(root)/_rootLayout/products/$slug'
import { Route as rootRootLayoutCategoriesSlugRouteImport } from './routes/(root)/_rootLayout/categories/$slug'
import { Route as authAuthVendorRegisterRouteImport } from './routes/(auth)/_auth/vendor/register'
import { Route as authAuthVendorLoginRouteImport } from './routes/(auth)/_auth/vendor/login'
import { Route as authAuthAdminResetPasswordRouteImport } from './routes/(auth)/_auth/admin/reset-password'
import { Route as authAuthAdminRegisterRouteImport } from './routes/(auth)/_auth/admin/register'
import { Route as authAuthAdminLoginRouteImport } from './routes/(auth)/_auth/admin/login'
import { Route as authAuthAdminForgotPasswordRouteImport } from './routes/(auth)/_auth/admin/forgot-password'
import { Route as adminAdminAdminLayoutProductsRouteImport } from './routes/(admin)/admin/_adminLayout/products'
import { Route as vendorVendorVendorLayoutWalletIndexRouteImport } from './routes/(vendor)/vendor/_vendorLayout/wallet/index'
import { Route as vendorVendorVendorLayoutSettingsIndexRouteImport } from './routes/(vendor)/vendor/_vendorLayout/settings/index'
import { Route as vendorVendorVendorLayoutProductsIndexRouteImport } from './routes/(vendor)/vendor/_vendorLayout/products/index'
import { Route as vendorVendorVendorLayoutOrdersIndexRouteImport } from './routes/(vendor)/vendor/_vendorLayout/orders/index'
import { Route as rootRootLayoutAuthenticatedOrdersIndexRouteImport } from './routes/(root)/_rootLayout/_authenticated/orders/index'
import { Route as rootRootLayoutAuthenticatedCartIndexRouteImport } from './routes/(root)/_rootLayout/_authenticated/cart/index'
import { Route as rootRootLayoutAuthenticatedAccountIndexRouteImport } from './routes/(root)/_rootLayout/_authenticated/account/index'
import { Route as vendorVendorVendorLayoutProductsNewRouteImport } from './routes/(vendor)/vendor/_vendorLayout/products/new'
import { Route as vendorVendorVendorLayoutProductsSlugRouteImport } from './routes/(vendor)/vendor/_vendorLayout/products/$slug'
import { Route as vendorVendorVendorLayoutOrdersOrderIdRouteImport } from './routes/(vendor)/vendor/_vendorLayout/orders/$orderId'
import { Route as rootRootLayoutAuthenticatedOrdersOrderIdRouteImport } from './routes/(root)/_rootLayout/_authenticated/orders/$orderId'
import { Route as rootRootLayoutAuthenticatedCartPaymentStatusRouteImport } from './routes/(root)/_rootLayout/_authenticated/cart/payment-status'
import { Route as rootRootLayoutAuthenticatedCartCheckoutRouteImport } from './routes/(root)/_rootLayout/_authenticated/cart/checkout'

const rootRootLayoutRoute = rootRootLayoutRouteImport.update({
  id: '/(root)/_rootLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRootLayoutIndexRoute = rootRootLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const vendorVendorVendorLayoutRoute =
  vendorVendorVendorLayoutRouteImport.update({
    id: '/(vendor)/vendor/_vendorLayout',
    path: '/vendor',
    getParentRoute: () => rootRouteImport,
  } as any)
const rootRootLayoutTermsRoute = rootRootLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutSearchRoute = rootRootLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutPrivacyRoute = rootRootLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutCookiesRoute = rootRootLayoutCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutContactRoute = rootRootLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRootLayoutRoute,
} as any)
const rootRootLayoutAuthenticatedRoute =
  rootRootLayoutAuthenticatedRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthResetPasswordRoute = authAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authAuthRoute,
} as any)
const adminAdminAdminLayoutRoute = adminAdminAdminLayoutRouteImport.update({
  id: '/(admin)/admin/_adminLayout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const vendorVendorVendorLayoutIndexRoute =
  vendorVendorVendorLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const rootRootLayoutProductsIndexRoute =
  rootRootLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const rootRootLayoutCategoriesIndexRoute =
  rootRootLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const adminAdminAdminLayoutIndexRoute =
  adminAdminAdminLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminAdminAdminLayoutRoute,
  } as any)
const rootRootLayoutProductsSlugRoute =
  rootRootLayoutProductsSlugRouteImport.update({
    id: '/products/$slug',
    path: '/products/$slug',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const rootRootLayoutCategoriesSlugRoute =
  rootRootLayoutCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => rootRootLayoutRoute,
  } as any)
const authAuthVendorRegisterRoute = authAuthVendorRegisterRouteImport.update({
  id: '/vendor/register',
  path: '/vendor/register',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthVendorLoginRoute = authAuthVendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAdminResetPasswordRoute =
  authAuthAdminResetPasswordRouteImport.update({
    id: '/admin/reset-password',
    path: '/admin/reset-password',
    getParentRoute: () => authAuthRoute,
  } as any)
const authAuthAdminRegisterRoute = authAuthAdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAdminLoginRoute = authAuthAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAdminForgotPasswordRoute =
  authAuthAdminForgotPasswordRouteImport.update({
    id: '/admin/forgot-password',
    path: '/admin/forgot-password',
    getParentRoute: () => authAuthRoute,
  } as any)
const adminAdminAdminLayoutProductsRoute =
  adminAdminAdminLayoutProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => adminAdminAdminLayoutRoute,
  } as any)
const vendorVendorVendorLayoutWalletIndexRoute =
  vendorVendorVendorLayoutWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const vendorVendorVendorLayoutSettingsIndexRoute =
  vendorVendorVendorLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const vendorVendorVendorLayoutProductsIndexRoute =
  vendorVendorVendorLayoutProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const vendorVendorVendorLayoutOrdersIndexRoute =
  vendorVendorVendorLayoutOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const rootRootLayoutAuthenticatedOrdersIndexRoute =
  rootRootLayoutAuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedCartIndexRoute =
  rootRootLayoutAuthenticatedCartIndexRouteImport.update({
    id: '/cart/',
    path: '/cart/',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedAccountIndexRoute =
  rootRootLayoutAuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const vendorVendorVendorLayoutProductsNewRoute =
  vendorVendorVendorLayoutProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const vendorVendorVendorLayoutProductsSlugRoute =
  vendorVendorVendorLayoutProductsSlugRouteImport.update({
    id: '/products/$slug',
    path: '/products/$slug',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const vendorVendorVendorLayoutOrdersOrderIdRoute =
  vendorVendorVendorLayoutOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => vendorVendorVendorLayoutRoute,
  } as any)
const rootRootLayoutAuthenticatedOrdersOrderIdRoute =
  rootRootLayoutAuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedCartPaymentStatusRoute =
  rootRootLayoutAuthenticatedCartPaymentStatusRouteImport.update({
    id: '/cart/payment-status',
    path: '/cart/payment-status',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)
const rootRootLayoutAuthenticatedCartCheckoutRoute =
  rootRootLayoutAuthenticatedCartCheckoutRouteImport.update({
    id: '/cart/checkout',
    path: '/cart/checkout',
    getParentRoute: () => rootRootLayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof adminAdminAdminLayoutRouteWithChildren
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/login': typeof authAuthLoginRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/signup': typeof authAuthSignupRoute
  '/contact': typeof rootRootLayoutContactRoute
  '/cookies': typeof rootRootLayoutCookiesRoute
  '/privacy': typeof rootRootLayoutPrivacyRoute
  '/search': typeof rootRootLayoutSearchRoute
  '/terms': typeof rootRootLayoutTermsRoute
  '/vendor': typeof vendorVendorVendorLayoutRouteWithChildren
  '/': typeof rootRootLayoutIndexRoute
  '/admin/products': typeof adminAdminAdminLayoutProductsRoute
  '/admin/forgot-password': typeof authAuthAdminForgotPasswordRoute
  '/admin/login': typeof authAuthAdminLoginRoute
  '/admin/register': typeof authAuthAdminRegisterRoute
  '/admin/reset-password': typeof authAuthAdminResetPasswordRoute
  '/vendor/login': typeof authAuthVendorLoginRoute
  '/vendor/register': typeof authAuthVendorRegisterRoute
  '/categories/$slug': typeof rootRootLayoutCategoriesSlugRoute
  '/products/$slug': typeof rootRootLayoutProductsSlugRoute
  '/admin/': typeof adminAdminAdminLayoutIndexRoute
  '/categories': typeof rootRootLayoutCategoriesIndexRoute
  '/products': typeof rootRootLayoutProductsIndexRoute
  '/vendor/': typeof vendorVendorVendorLayoutIndexRoute
  '/cart/checkout': typeof rootRootLayoutAuthenticatedCartCheckoutRoute
  '/cart/payment-status': typeof rootRootLayoutAuthenticatedCartPaymentStatusRoute
  '/orders/$orderId': typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  '/vendor/orders/$orderId': typeof vendorVendorVendorLayoutOrdersOrderIdRoute
  '/vendor/products/$slug': typeof vendorVendorVendorLayoutProductsSlugRoute
  '/vendor/products/new': typeof vendorVendorVendorLayoutProductsNewRoute
  '/account': typeof rootRootLayoutAuthenticatedAccountIndexRoute
  '/cart': typeof rootRootLayoutAuthenticatedCartIndexRoute
  '/orders': typeof rootRootLayoutAuthenticatedOrdersIndexRoute
  '/vendor/orders': typeof vendorVendorVendorLayoutOrdersIndexRoute
  '/vendor/products': typeof vendorVendorVendorLayoutProductsIndexRoute
  '/vendor/settings': typeof vendorVendorVendorLayoutSettingsIndexRoute
  '/vendor/wallet': typeof vendorVendorVendorLayoutWalletIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authAuthForgotPasswordRoute
  '/login': typeof authAuthLoginRoute
  '/reset-password': typeof authAuthResetPasswordRoute
  '/signup': typeof authAuthSignupRoute
  '/contact': typeof rootRootLayoutContactRoute
  '/cookies': typeof rootRootLayoutCookiesRoute
  '/privacy': typeof rootRootLayoutPrivacyRoute
  '/search': typeof rootRootLayoutSearchRoute
  '/terms': typeof rootRootLayoutTermsRoute
  '/': typeof rootRootLayoutIndexRoute
  '/admin/products': typeof adminAdminAdminLayoutProductsRoute
  '/admin/forgot-password': typeof authAuthAdminForgotPasswordRoute
  '/admin/login': typeof authAuthAdminLoginRoute
  '/admin/register': typeof authAuthAdminRegisterRoute
  '/admin/reset-password': typeof authAuthAdminResetPasswordRoute
  '/vendor/login': typeof authAuthVendorLoginRoute
  '/vendor/register': typeof authAuthVendorRegisterRoute
  '/categories/$slug': typeof rootRootLayoutCategoriesSlugRoute
  '/products/$slug': typeof rootRootLayoutProductsSlugRoute
  '/admin': typeof adminAdminAdminLayoutIndexRoute
  '/categories': typeof rootRootLayoutCategoriesIndexRoute
  '/products': typeof rootRootLayoutProductsIndexRoute
  '/vendor': typeof vendorVendorVendorLayoutIndexRoute
  '/cart/checkout': typeof rootRootLayoutAuthenticatedCartCheckoutRoute
  '/cart/payment-status': typeof rootRootLayoutAuthenticatedCartPaymentStatusRoute
  '/orders/$orderId': typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  '/vendor/orders/$orderId': typeof vendorVendorVendorLayoutOrdersOrderIdRoute
  '/vendor/products/$slug': typeof vendorVendorVendorLayoutProductsSlugRoute
  '/vendor/products/new': typeof vendorVendorVendorLayoutProductsNewRoute
  '/account': typeof rootRootLayoutAuthenticatedAccountIndexRoute
  '/cart': typeof rootRootLayoutAuthenticatedCartIndexRoute
  '/orders': typeof rootRootLayoutAuthenticatedOrdersIndexRoute
  '/vendor/orders': typeof vendorVendorVendorLayoutOrdersIndexRoute
  '/vendor/products': typeof vendorVendorVendorLayoutProductsIndexRoute
  '/vendor/settings': typeof vendorVendorVendorLayoutSettingsIndexRoute
  '/vendor/wallet': typeof vendorVendorVendorLayoutWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(root)/_rootLayout': typeof rootRootLayoutRouteWithChildren
  '/(admin)/admin/_adminLayout': typeof adminAdminAdminLayoutRouteWithChildren
  '/(auth)/_auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(auth)/_auth/reset-password': typeof authAuthResetPasswordRoute
  '/(auth)/_auth/signup': typeof authAuthSignupRoute
  '/(root)/_rootLayout/_authenticated': typeof rootRootLayoutAuthenticatedRouteWithChildren
  '/(root)/_rootLayout/contact': typeof rootRootLayoutContactRoute
  '/(root)/_rootLayout/cookies': typeof rootRootLayoutCookiesRoute
  '/(root)/_rootLayout/privacy': typeof rootRootLayoutPrivacyRoute
  '/(root)/_rootLayout/search': typeof rootRootLayoutSearchRoute
  '/(root)/_rootLayout/terms': typeof rootRootLayoutTermsRoute
  '/(vendor)/vendor/_vendorLayout': typeof vendorVendorVendorLayoutRouteWithChildren
  '/(root)/_rootLayout/': typeof rootRootLayoutIndexRoute
  '/(admin)/admin/_adminLayout/products': typeof adminAdminAdminLayoutProductsRoute
  '/(auth)/_auth/admin/forgot-password': typeof authAuthAdminForgotPasswordRoute
  '/(auth)/_auth/admin/login': typeof authAuthAdminLoginRoute
  '/(auth)/_auth/admin/register': typeof authAuthAdminRegisterRoute
  '/(auth)/_auth/admin/reset-password': typeof authAuthAdminResetPasswordRoute
  '/(auth)/_auth/vendor/login': typeof authAuthVendorLoginRoute
  '/(auth)/_auth/vendor/register': typeof authAuthVendorRegisterRoute
  '/(root)/_rootLayout/categories/$slug': typeof rootRootLayoutCategoriesSlugRoute
  '/(root)/_rootLayout/products/$slug': typeof rootRootLayoutProductsSlugRoute
  '/(admin)/admin/_adminLayout/': typeof adminAdminAdminLayoutIndexRoute
  '/(root)/_rootLayout/categories/': typeof rootRootLayoutCategoriesIndexRoute
  '/(root)/_rootLayout/products/': typeof rootRootLayoutProductsIndexRoute
  '/(vendor)/vendor/_vendorLayout/': typeof vendorVendorVendorLayoutIndexRoute
  '/(root)/_rootLayout/_authenticated/cart/checkout': typeof rootRootLayoutAuthenticatedCartCheckoutRoute
  '/(root)/_rootLayout/_authenticated/cart/payment-status': typeof rootRootLayoutAuthenticatedCartPaymentStatusRoute
  '/(root)/_rootLayout/_authenticated/orders/$orderId': typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  '/(vendor)/vendor/_vendorLayout/orders/$orderId': typeof vendorVendorVendorLayoutOrdersOrderIdRoute
  '/(vendor)/vendor/_vendorLayout/products/$slug': typeof vendorVendorVendorLayoutProductsSlugRoute
  '/(vendor)/vendor/_vendorLayout/products/new': typeof vendorVendorVendorLayoutProductsNewRoute
  '/(root)/_rootLayout/_authenticated/account/': typeof rootRootLayoutAuthenticatedAccountIndexRoute
  '/(root)/_rootLayout/_authenticated/cart/': typeof rootRootLayoutAuthenticatedCartIndexRoute
  '/(root)/_rootLayout/_authenticated/orders/': typeof rootRootLayoutAuthenticatedOrdersIndexRoute
  '/(vendor)/vendor/_vendorLayout/orders/': typeof vendorVendorVendorLayoutOrdersIndexRoute
  '/(vendor)/vendor/_vendorLayout/products/': typeof vendorVendorVendorLayoutProductsIndexRoute
  '/(vendor)/vendor/_vendorLayout/settings/': typeof vendorVendorVendorLayoutSettingsIndexRoute
  '/(vendor)/vendor/_vendorLayout/wallet/': typeof vendorVendorVendorLayoutWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/vendor'
    | '/'
    | '/admin/products'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/register'
    | '/admin/reset-password'
    | '/vendor/login'
    | '/vendor/register'
    | '/categories/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/categories'
    | '/products'
    | '/vendor/'
    | '/cart/checkout'
    | '/cart/payment-status'
    | '/orders/$orderId'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$slug'
    | '/vendor/products/new'
    | '/account'
    | '/cart'
    | '/orders'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/vendor/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/'
    | '/admin/products'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/register'
    | '/admin/reset-password'
    | '/vendor/login'
    | '/vendor/register'
    | '/categories/$slug'
    | '/products/$slug'
    | '/admin'
    | '/categories'
    | '/products'
    | '/vendor'
    | '/cart/checkout'
    | '/cart/payment-status'
    | '/orders/$orderId'
    | '/vendor/orders/$orderId'
    | '/vendor/products/$slug'
    | '/vendor/products/new'
    | '/account'
    | '/cart'
    | '/orders'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/vendor/wallet'
  id:
    | '__root__'
    | '/(auth)/_auth'
    | '/(root)/_rootLayout'
    | '/(admin)/admin/_adminLayout'
    | '/(auth)/_auth/forgot-password'
    | '/(auth)/_auth/login'
    | '/(auth)/_auth/reset-password'
    | '/(auth)/_auth/signup'
    | '/(root)/_rootLayout/_authenticated'
    | '/(root)/_rootLayout/contact'
    | '/(root)/_rootLayout/cookies'
    | '/(root)/_rootLayout/privacy'
    | '/(root)/_rootLayout/search'
    | '/(root)/_rootLayout/terms'
    | '/(vendor)/vendor/_vendorLayout'
    | '/(root)/_rootLayout/'
    | '/(admin)/admin/_adminLayout/products'
    | '/(auth)/_auth/admin/forgot-password'
    | '/(auth)/_auth/admin/login'
    | '/(auth)/_auth/admin/register'
    | '/(auth)/_auth/admin/reset-password'
    | '/(auth)/_auth/vendor/login'
    | '/(auth)/_auth/vendor/register'
    | '/(root)/_rootLayout/categories/$slug'
    | '/(root)/_rootLayout/products/$slug'
    | '/(admin)/admin/_adminLayout/'
    | '/(root)/_rootLayout/categories/'
    | '/(root)/_rootLayout/products/'
    | '/(vendor)/vendor/_vendorLayout/'
    | '/(root)/_rootLayout/_authenticated/cart/checkout'
    | '/(root)/_rootLayout/_authenticated/cart/payment-status'
    | '/(root)/_rootLayout/_authenticated/orders/$orderId'
    | '/(vendor)/vendor/_vendorLayout/orders/$orderId'
    | '/(vendor)/vendor/_vendorLayout/products/$slug'
    | '/(vendor)/vendor/_vendorLayout/products/new'
    | '/(root)/_rootLayout/_authenticated/account/'
    | '/(root)/_rootLayout/_authenticated/cart/'
    | '/(root)/_rootLayout/_authenticated/orders/'
    | '/(vendor)/vendor/_vendorLayout/orders/'
    | '/(vendor)/vendor/_vendorLayout/products/'
    | '/(vendor)/vendor/_vendorLayout/settings/'
    | '/(vendor)/vendor/_vendorLayout/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
  rootRootLayoutRoute: typeof rootRootLayoutRouteWithChildren
  adminAdminAdminLayoutRoute: typeof adminAdminAdminLayoutRouteWithChildren
  vendorVendorVendorLayoutRoute: typeof vendorVendorVendorLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root)/_rootLayout': {
      id: '/(root)/_rootLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRootLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/_rootLayout/': {
      id: '/(root)/_rootLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootRootLayoutIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(vendor)/vendor/_vendorLayout': {
      id: '/(vendor)/vendor/_vendorLayout'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof vendorVendorVendorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/_rootLayout/terms': {
      id: '/(root)/_rootLayout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof rootRootLayoutTermsRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/search': {
      id: '/(root)/_rootLayout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof rootRootLayoutSearchRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/privacy': {
      id: '/(root)/_rootLayout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof rootRootLayoutPrivacyRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/cookies': {
      id: '/(root)/_rootLayout/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof rootRootLayoutCookiesRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/contact': {
      id: '/(root)/_rootLayout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof rootRootLayoutContactRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/_authenticated': {
      id: '/(root)/_rootLayout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRootLayoutAuthenticatedRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(auth)/_auth/signup': {
      id: '/(auth)/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/reset-password': {
      id: '/(auth)/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authAuthResetPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/forgot-password': {
      id: '/(auth)/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(admin)/admin/_adminLayout': {
      id: '/(admin)/admin/_adminLayout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminAdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(vendor)/vendor/_vendorLayout/': {
      id: '/(vendor)/vendor/_vendorLayout/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof vendorVendorVendorLayoutIndexRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(root)/_rootLayout/products/': {
      id: '/(root)/_rootLayout/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof rootRootLayoutProductsIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/categories/': {
      id: '/(root)/_rootLayout/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof rootRootLayoutCategoriesIndexRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(admin)/admin/_adminLayout/': {
      id: '/(admin)/admin/_adminLayout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminAdminLayoutIndexRouteImport
      parentRoute: typeof adminAdminAdminLayoutRoute
    }
    '/(root)/_rootLayout/products/$slug': {
      id: '/(root)/_rootLayout/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof rootRootLayoutProductsSlugRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(root)/_rootLayout/categories/$slug': {
      id: '/(root)/_rootLayout/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof rootRootLayoutCategoriesSlugRouteImport
      parentRoute: typeof rootRootLayoutRoute
    }
    '/(auth)/_auth/vendor/register': {
      id: '/(auth)/_auth/vendor/register'
      path: '/vendor/register'
      fullPath: '/vendor/register'
      preLoaderRoute: typeof authAuthVendorRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/vendor/login': {
      id: '/(auth)/_auth/vendor/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof authAuthVendorLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/reset-password': {
      id: '/(auth)/_auth/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof authAuthAdminResetPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/register': {
      id: '/(auth)/_auth/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof authAuthAdminRegisterRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/login': {
      id: '/(auth)/_auth/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof authAuthAdminLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/admin/forgot-password': {
      id: '/(auth)/_auth/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof authAuthAdminForgotPasswordRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(admin)/admin/_adminLayout/products': {
      id: '/(admin)/admin/_adminLayout/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof adminAdminAdminLayoutProductsRouteImport
      parentRoute: typeof adminAdminAdminLayoutRoute
    }
    '/(vendor)/vendor/_vendorLayout/wallet/': {
      id: '/(vendor)/vendor/_vendorLayout/wallet/'
      path: '/wallet'
      fullPath: '/vendor/wallet'
      preLoaderRoute: typeof vendorVendorVendorLayoutWalletIndexRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(vendor)/vendor/_vendorLayout/settings/': {
      id: '/(vendor)/vendor/_vendorLayout/settings/'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof vendorVendorVendorLayoutSettingsIndexRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(vendor)/vendor/_vendorLayout/products/': {
      id: '/(vendor)/vendor/_vendorLayout/products/'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof vendorVendorVendorLayoutProductsIndexRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(vendor)/vendor/_vendorLayout/orders/': {
      id: '/(vendor)/vendor/_vendorLayout/orders/'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof vendorVendorVendorLayoutOrdersIndexRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(root)/_rootLayout/_authenticated/orders/': {
      id: '/(root)/_rootLayout/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedOrdersIndexRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/cart/': {
      id: '/(root)/_rootLayout/_authenticated/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedCartIndexRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/account/': {
      id: '/(root)/_rootLayout/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedAccountIndexRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(vendor)/vendor/_vendorLayout/products/new': {
      id: '/(vendor)/vendor/_vendorLayout/products/new'
      path: '/products/new'
      fullPath: '/vendor/products/new'
      preLoaderRoute: typeof vendorVendorVendorLayoutProductsNewRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(vendor)/vendor/_vendorLayout/products/$slug': {
      id: '/(vendor)/vendor/_vendorLayout/products/$slug'
      path: '/products/$slug'
      fullPath: '/vendor/products/$slug'
      preLoaderRoute: typeof vendorVendorVendorLayoutProductsSlugRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(vendor)/vendor/_vendorLayout/orders/$orderId': {
      id: '/(vendor)/vendor/_vendorLayout/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/vendor/orders/$orderId'
      preLoaderRoute: typeof vendorVendorVendorLayoutOrdersOrderIdRouteImport
      parentRoute: typeof vendorVendorVendorLayoutRoute
    }
    '/(root)/_rootLayout/_authenticated/orders/$orderId': {
      id: '/(root)/_rootLayout/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/cart/payment-status': {
      id: '/(root)/_rootLayout/_authenticated/cart/payment-status'
      path: '/cart/payment-status'
      fullPath: '/cart/payment-status'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedCartPaymentStatusRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
    '/(root)/_rootLayout/_authenticated/cart/checkout': {
      id: '/(root)/_rootLayout/_authenticated/cart/checkout'
      path: '/cart/checkout'
      fullPath: '/cart/checkout'
      preLoaderRoute: typeof rootRootLayoutAuthenticatedCartCheckoutRouteImport
      parentRoute: typeof rootRootLayoutAuthenticatedRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthResetPasswordRoute: typeof authAuthResetPasswordRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
  authAuthAdminForgotPasswordRoute: typeof authAuthAdminForgotPasswordRoute
  authAuthAdminLoginRoute: typeof authAuthAdminLoginRoute
  authAuthAdminRegisterRoute: typeof authAuthAdminRegisterRoute
  authAuthAdminResetPasswordRoute: typeof authAuthAdminResetPasswordRoute
  authAuthVendorLoginRoute: typeof authAuthVendorLoginRoute
  authAuthVendorRegisterRoute: typeof authAuthVendorRegisterRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthResetPasswordRoute: authAuthResetPasswordRoute,
  authAuthSignupRoute: authAuthSignupRoute,
  authAuthAdminForgotPasswordRoute: authAuthAdminForgotPasswordRoute,
  authAuthAdminLoginRoute: authAuthAdminLoginRoute,
  authAuthAdminRegisterRoute: authAuthAdminRegisterRoute,
  authAuthAdminResetPasswordRoute: authAuthAdminResetPasswordRoute,
  authAuthVendorLoginRoute: authAuthVendorLoginRoute,
  authAuthVendorRegisterRoute: authAuthVendorRegisterRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface rootRootLayoutAuthenticatedRouteChildren {
  rootRootLayoutAuthenticatedCartCheckoutRoute: typeof rootRootLayoutAuthenticatedCartCheckoutRoute
  rootRootLayoutAuthenticatedCartPaymentStatusRoute: typeof rootRootLayoutAuthenticatedCartPaymentStatusRoute
  rootRootLayoutAuthenticatedOrdersOrderIdRoute: typeof rootRootLayoutAuthenticatedOrdersOrderIdRoute
  rootRootLayoutAuthenticatedAccountIndexRoute: typeof rootRootLayoutAuthenticatedAccountIndexRoute
  rootRootLayoutAuthenticatedCartIndexRoute: typeof rootRootLayoutAuthenticatedCartIndexRoute
  rootRootLayoutAuthenticatedOrdersIndexRoute: typeof rootRootLayoutAuthenticatedOrdersIndexRoute
}

const rootRootLayoutAuthenticatedRouteChildren: rootRootLayoutAuthenticatedRouteChildren =
  {
    rootRootLayoutAuthenticatedCartCheckoutRoute:
      rootRootLayoutAuthenticatedCartCheckoutRoute,
    rootRootLayoutAuthenticatedCartPaymentStatusRoute:
      rootRootLayoutAuthenticatedCartPaymentStatusRoute,
    rootRootLayoutAuthenticatedOrdersOrderIdRoute:
      rootRootLayoutAuthenticatedOrdersOrderIdRoute,
    rootRootLayoutAuthenticatedAccountIndexRoute:
      rootRootLayoutAuthenticatedAccountIndexRoute,
    rootRootLayoutAuthenticatedCartIndexRoute:
      rootRootLayoutAuthenticatedCartIndexRoute,
    rootRootLayoutAuthenticatedOrdersIndexRoute:
      rootRootLayoutAuthenticatedOrdersIndexRoute,
  }

const rootRootLayoutAuthenticatedRouteWithChildren =
  rootRootLayoutAuthenticatedRoute._addFileChildren(
    rootRootLayoutAuthenticatedRouteChildren,
  )

interface rootRootLayoutRouteChildren {
  rootRootLayoutAuthenticatedRoute: typeof rootRootLayoutAuthenticatedRouteWithChildren
  rootRootLayoutContactRoute: typeof rootRootLayoutContactRoute
  rootRootLayoutCookiesRoute: typeof rootRootLayoutCookiesRoute
  rootRootLayoutPrivacyRoute: typeof rootRootLayoutPrivacyRoute
  rootRootLayoutSearchRoute: typeof rootRootLayoutSearchRoute
  rootRootLayoutTermsRoute: typeof rootRootLayoutTermsRoute
  rootRootLayoutIndexRoute: typeof rootRootLayoutIndexRoute
  rootRootLayoutCategoriesSlugRoute: typeof rootRootLayoutCategoriesSlugRoute
  rootRootLayoutProductsSlugRoute: typeof rootRootLayoutProductsSlugRoute
  rootRootLayoutCategoriesIndexRoute: typeof rootRootLayoutCategoriesIndexRoute
  rootRootLayoutProductsIndexRoute: typeof rootRootLayoutProductsIndexRoute
}

const rootRootLayoutRouteChildren: rootRootLayoutRouteChildren = {
  rootRootLayoutAuthenticatedRoute:
    rootRootLayoutAuthenticatedRouteWithChildren,
  rootRootLayoutContactRoute: rootRootLayoutContactRoute,
  rootRootLayoutCookiesRoute: rootRootLayoutCookiesRoute,
  rootRootLayoutPrivacyRoute: rootRootLayoutPrivacyRoute,
  rootRootLayoutSearchRoute: rootRootLayoutSearchRoute,
  rootRootLayoutTermsRoute: rootRootLayoutTermsRoute,
  rootRootLayoutIndexRoute: rootRootLayoutIndexRoute,
  rootRootLayoutCategoriesSlugRoute: rootRootLayoutCategoriesSlugRoute,
  rootRootLayoutProductsSlugRoute: rootRootLayoutProductsSlugRoute,
  rootRootLayoutCategoriesIndexRoute: rootRootLayoutCategoriesIndexRoute,
  rootRootLayoutProductsIndexRoute: rootRootLayoutProductsIndexRoute,
}

const rootRootLayoutRouteWithChildren = rootRootLayoutRoute._addFileChildren(
  rootRootLayoutRouteChildren,
)

interface adminAdminAdminLayoutRouteChildren {
  adminAdminAdminLayoutProductsRoute: typeof adminAdminAdminLayoutProductsRoute
  adminAdminAdminLayoutIndexRoute: typeof adminAdminAdminLayoutIndexRoute
}

const adminAdminAdminLayoutRouteChildren: adminAdminAdminLayoutRouteChildren = {
  adminAdminAdminLayoutProductsRoute: adminAdminAdminLayoutProductsRoute,
  adminAdminAdminLayoutIndexRoute: adminAdminAdminLayoutIndexRoute,
}

const adminAdminAdminLayoutRouteWithChildren =
  adminAdminAdminLayoutRoute._addFileChildren(
    adminAdminAdminLayoutRouteChildren,
  )

interface vendorVendorVendorLayoutRouteChildren {
  vendorVendorVendorLayoutIndexRoute: typeof vendorVendorVendorLayoutIndexRoute
  vendorVendorVendorLayoutOrdersOrderIdRoute: typeof vendorVendorVendorLayoutOrdersOrderIdRoute
  vendorVendorVendorLayoutProductsSlugRoute: typeof vendorVendorVendorLayoutProductsSlugRoute
  vendorVendorVendorLayoutProductsNewRoute: typeof vendorVendorVendorLayoutProductsNewRoute
  vendorVendorVendorLayoutOrdersIndexRoute: typeof vendorVendorVendorLayoutOrdersIndexRoute
  vendorVendorVendorLayoutProductsIndexRoute: typeof vendorVendorVendorLayoutProductsIndexRoute
  vendorVendorVendorLayoutSettingsIndexRoute: typeof vendorVendorVendorLayoutSettingsIndexRoute
  vendorVendorVendorLayoutWalletIndexRoute: typeof vendorVendorVendorLayoutWalletIndexRoute
}

const vendorVendorVendorLayoutRouteChildren: vendorVendorVendorLayoutRouteChildren =
  {
    vendorVendorVendorLayoutIndexRoute: vendorVendorVendorLayoutIndexRoute,
    vendorVendorVendorLayoutOrdersOrderIdRoute:
      vendorVendorVendorLayoutOrdersOrderIdRoute,
    vendorVendorVendorLayoutProductsSlugRoute:
      vendorVendorVendorLayoutProductsSlugRoute,
    vendorVendorVendorLayoutProductsNewRoute:
      vendorVendorVendorLayoutProductsNewRoute,
    vendorVendorVendorLayoutOrdersIndexRoute:
      vendorVendorVendorLayoutOrdersIndexRoute,
    vendorVendorVendorLayoutProductsIndexRoute:
      vendorVendorVendorLayoutProductsIndexRoute,
    vendorVendorVendorLayoutSettingsIndexRoute:
      vendorVendorVendorLayoutSettingsIndexRoute,
    vendorVendorVendorLayoutWalletIndexRoute:
      vendorVendorVendorLayoutWalletIndexRoute,
  }

const vendorVendorVendorLayoutRouteWithChildren =
  vendorVendorVendorLayoutRoute._addFileChildren(
    vendorVendorVendorLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
  rootRootLayoutRoute: rootRootLayoutRouteWithChildren,
  adminAdminAdminLayoutRoute: adminAdminAdminLayoutRouteWithChildren,
  vendorVendorVendorLayoutRoute: vendorVendorVendorLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
